name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: install Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        if: inputs.rust == 'true'
        with:
          toolchain: stable

      - name: install dependencies (ubuntu only)
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: (matrix.platform == 'ubuntu-latest')
        with:
          packages: libwebkit2gtk-4.1-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
          version: 1.0

      - name: yarn install
        run: yarn install
        shell: "bash"

      - name: yarn tailwind
        run: yarn tailwind
        shell: "bash"

      - name: install tauri-cli
        run: cargo install tauri-cli

      - name: install trunk
        run: cargo install trunk

      - name: build
        run: cargo tauri build

      - name: upload artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: tauri-src/target/release/bundle
